DM-47759: Initial text
lsst-dm/dmtn-302 pull request #1
Opened 2024-11-22 20:25 UTC by timj

2024-12-02 22:00 UTC, gpdf requested changes
Partial notes from today's Arch team meeting

2024-12-02 22:00 UTC, gpdf commented on index.md
> +* `org.rubinobs`
Chose `org.rubinobs` today

2024-12-02 22:00 UTC, gpdf commented on index.md
> +## Resource Key
Agreed today to include the DAC identity as the first /-delimited element of the resource key.  Specifically, `usdac` for the data access services at the US DAC at the USDF.

2024-12-02 22:00 UTC, gpdf commented on index.md
> +* `?repo=/repo/main&id=UUID`
Agreed today to favor this style.  `repo=` values will normally be single tokens without a leading "/".

2025-03-07 18:05 UTC, timj commented on index.md
> +* `ivo://org.rubinobs/usdac/dr1?repo=dr1&id=UUID`
This has to be `lsst-dr1?`

2025-03-07 18:06 UTC, timj commented on index.md
> +* `ivo://org.rubinobs/usdac/dp1?type=object&release=dp1&id=OBJECTID`
Object should be on the left her because the registry will be tracking the tables.

2025-06-04 02:24 UTC, gpdf approved these changes
It's very confusing because I made some "pending" comments a long time ago that never got published, but I went through them and I think a couple are still applicable.  I deleted one that was in conflict with the way I wrote things today.

2025-06-04 02:24 UTC, gpdf commented on index.md
> +This suggests Rubin should consider:
```suggestion
The following options were considered for use for the initial LSST data releases:
```

2025-06-04 02:24 UTC, gpdf commented on index.md
> +
```suggestion

IVOIDs are used in the ObsCore standard, in particular, for the following fields: `obs_publisher_did`, `obs_creator_did`, and `publisher_id`.  The roles of these fields, and how we will use them, are discussed below.
```

2025-06-04 02:24 UTC, gpdf commented on index.md
> +
```suggestion

The intent is that a full IVOID for a dataset (e.g., from an ObsCore `obs_publisher_did`) should be usable to drive a Butler lookup of that dataset.  
(This assumes backward compatibility, at least at the level of the ability to perform a `Butler.get()` operation, if not to run the pipelines.)
Note that UUIDs are already expected to remain stable across export/import of data from its "Butler of origin" to others, e.g., at remote DACs.
```

2025-06-04 02:24 UTC, gpdf commented on index.md
> +## Resource Key
Agreed in the end to do this for obs_publisher_did style IVOIDs

2025-06-04 02:24 UTC, gpdf commented on index.md
> +* `ivo://org.rubinobs/usdac/dr1?repo=dr1&id=UUID`
As agreed, yes

2025-06-04 02:24 UTC, gpdf commented on index.md
> +* `ivo://org.rubinobs/usdac/dp1?type=object&release=dp1&id=OBJECTID`
Still need to think about whether to have registry entries for tables or just have them be "resources" under the DR.

2025-06-04 02:44 UTC, merged